---
abstract: 'A simple OAI data provider'
author:
  - 'Maurice Mengel <mauricemengel@gmail.com>'
build_requires:
  English: 0
  FindBin: 0
  Test::More: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-OAI-DataProvider
requires:
  Carp: 0
  DBI: 0
  DBIx::Connector: 0
  Dancer: 0
  Dancer::CommandLine: 0
  Encode: 0
  Exporter: 0
  HTTP::OAI: 0
  HTTP::OAI::Repository: 0
  Time::HiRes: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  XML::LibXSLT: 0
  XML::SAX::Writer: 0
  YAML::Syck: 0
  parent: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=HTTP-OAI-DataProvider
  homepage: https://github.com/mokko/HTTP-OAI-DataProvider/wiki
  repository: git://github.com/mokko/HTTP-OAI-DataProvider.git
version: 0.006
